version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ritik
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: dynamicJobs
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init_db.sql

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      POSTGRES_URL: postgresql://ritik:1234@localhost:5432/dynamicJobs

volumes:
  db-data:
